### ISSUE TITLE
How to set #define for a library that means to be included in a .c file

### ISSUE THREAD

**Issue by norman784** [JetBrains/kotlin-native#1622]
I'm trying to create a binding for [nuklear](https://github.com/vurtun/nuklear) and that library is single header (so we really don't have any lib, the lib lives in the header), I'm able to create the binding without issues, besides that I need some defines to enable some functionality:

```
/* nuklear - 1.32.0 - public domain */
...
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_IMPLEMENTATION
#include "nuklear.h"
...
```

*For more context this code was took from [sdl implementation](https://github.com/vurtun/nuklear/blob/master/demo/sdl_opengl3/main.c), just for the sake fo simplicity between the other implementations.*

But note that to enable features you need to use `#define` follow by one of the `NK_*` constant (if I'm not mistaken), for an example on how [go binding do](https://github.com/golang-ui/nuklear/blob/master/nk.yml) (don't know if I can define const in the .def file)

```
...
PARSER:
  IncludePaths: ["/usr/include", "/usr/local/include"]
  SourcesPaths: ["nk/nuklear.h"]
  Defines:
    NK_INCLUDE_FIXED_TYPES: 1
    NK_INCLUDE_STANDARD_IO: 1
    NK_INCLUDE_DEFAULT_ALLOCATOR: 1
    NK_INCLUDE_FONT_BAKING: 1
    NK_INCLUDE_DEFAULT_FONT: 1
    NK_INCLUDE_VERTEX_BUFFER_OUTPUT: 1
...
```

So the questions are:

1- How to define a constant (I'm really not sure if `#defile NK_*` is a constant, but from my understanding is, correct me if I'm wrong) to compile with the c header? (Tried also to include that header into another header with those constants but seems that theres some conflict if I do so and it wont compile)

2- Theres any doc for .def files?

Regards
